### ISSUE TITLE
Are the metrics created standard or high resolution?

### ISSUE THREAD

**Issue by andybalham** [awslabs/aws-embedded-metrics-node#108]
The AWS [Publishing custom metrics](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/publishingMetrics.html) page mentions standard and high resolution metrics. I have had a look through the documentation and source code for this package and can find no mention of either.

I am wanting to write a blog post about this package, but want to be clear to any reader what the granularity of the resulting metrics will be.

Thanks

**Comment by jaredcnance** [comment]
EMF currently only supports standard resolution metrics.
