### ISSUE TITLE
"Cannot call write after a stream was destroyed" on ECS

### ISSUE THREAD

**Issue by PascalPflaum** [awslabs/aws-embedded-metrics-node#120]
I noticed many messages like the following on a production ECS system, after Upgrading from node 14 to node 16.15.0
Roundabout 1/3 of all writes fail with this message.

`{
        "message": "Cannot call write after a stream was destroyed",
        "name": "Error",
        "stack": "Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed\n    at new NodeError (node:internal/errors:372:5)\n    at _write (node:internal/streams/writable:321:11)\n    at Socket.Writable.write (node:internal/streams/writable:334:10)\n    at /thingregistry/node_modules/aws-embedded-metrics/lib/sinks/connections/TcpClient.js:58:56\n    at new Promise (<anonymous>)\n    at TcpClient.<anonymous> (/thingregistry/node_modules/aws-embedded-metrics/lib/sinks/connections/TcpClient.js:53:19)\n    at Generator.next (<anonymous>)\n    at fulfilled (/thingregistry/node_modules/aws-embedded-metrics/lib/sinks/connections/TcpClient.js:19:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
        "code": "ERR_STREAM_DESTROYED"
    }`

I could not find any obvious issue in the code.

**Comment by danielrhodes** [comment]
+ 1
Also seeing this.

**Comment by lexedwards** [comment]
+1 also seeing this occure

**Comment by davidweimapbox** [comment]
+1 same here

**Comment by davidweimapbox** [comment]
Awesome! Thanks for the quick fix!  @markkuhn Can we expect a new release v2.0.6 soon as this is a blocking issue in our team after we upgraded to node 16.

**Comment by markkuhn** [comment]
Hi @davidweimapbox . We will be releasing v2.0.6 in a day or two!

**Comment by davidweimapbox** [comment]
@markkuhn Cool! thanks for confirm!

**Comment by markkuhn** [comment]
Package has been published. Thank you for the report @PascalPflaum !
