### ISSUE TITLE
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed

### ISSUE THREAD

**Issue by davidweimapbox** [awslabs/aws-embedded-metrics-node#129]
This issue might be still related to 
https://github.com/awslabs/aws-embedded-metrics-node/issues/120. @markkuhn

After we bumped up to the latest v2.0.6, still see the same error in Cloudwatch.

<img width="1128" alt="image" src="https://user-images.githubusercontent.com/102546362/181616620-41e29d57-08cb-41c4-97e8-74f949a6a84a.png">

The issue is only in our stacks with node v16,  no issue for stacks in node v14.

**Comment by markkuhn** [comment]
Can you give me a bit more information so that I can reproduce this locally?

**Comment by davidweimapbox** [comment]
Actually, when I run our stack locally, I can see the metrics created, no any errors in console log. However, after we deploy the stack to AWS,   the errors keep showing in the Cloudwatch logs. We are in node v16.16.  Not sure how to reproduce it locally, maybe in docker?

**Comment by markkuhn** [comment]
Are you running it in EC2, ECS, EKS or Lambda?

**Comment by davidweimapbox** [comment]
We are using this module via a wrapper component, I am going to double check if the issue is on our side first. Will close this ticket to avoid wasting your time. Thanks for the great help and quick response on the bug fixing! @markkuhn
