### ISSUE TITLE
Undocumented release 3.0.0 

### ISSUE THREAD

**Issue by PascalPflaum** [awslabs/aws-embedded-metrics-node#130]
I noticed the release of an undocumented change as new major version on npm in the last 24 hours.

> dist
> .tarball: https://bahnhub.tech.rz.db.de:443/artifactory/api/npm/default-npm-3rdparty/aws-embedded-metrics/-/aws-embedded-metrics-3.0.0.tgz
> .shasum: 0ecbd9e1411195ceef289109853ea4ac9e71626d
> .integrity: sha512-4SsOynlnrdT9C8NzQFLqyIz/5g/sYPYsKF1yh+VcnIIMliXHt1CHZS4Gw0Gd0IDZLPS+sWrL6jyAzPvsaog7sg==

Securitywise the change does not look critical, still having a release with a change not mentioned in the Release Notes seems to be a red flag. https://github.com/awslabs/aws-embedded-metrics-node/releases

**Comment by Himtanaya** [comment]
Apologies for the delay in documentation. The new release tag is now created.
