### ISSUE TITLE
ES Module and Validator package

### ISSUE THREAD

**Issue by thantos** [awslabs/aws-embedded-metrics-node#140]
Are there plans to publish an ESM and tree shaken version of the package? 

EMF is ~300kb without compression with 200kb just for the new `validator` dependency, most of which is not being used.

With SDK V3 being supported in Node18 on Lambda, EMF is now 90% of my bundle.

**Comment by sam-goodwin** [comment]
Any update on this? The Node community is bundle conscious and a metric client adding 200KB is excessive. Any plan to fix?

**Comment by markkuhn** [comment]
Thanks for reporting this.
The validator dependency has been removed.

**Comment by sam-goodwin** [comment]
Happy to see this roll out! To pile on, I'm curious if there are any plans to include EMF in the lambda runtime image? Seems like one of those super common things everyone needs?
