### ISSUE TITLE
Calling flush would reset the namespace as well

### ISSUE THREAD

**Issue by jouyang** [awslabs/aws-embedded-metrics-node#15]
Documentation for flush()

>flush()
Flushes the current MetricsContext to the configured sink and resets all properties, dimensions and metric values. The namespace and default dimensions will be preserved across flushes.

Namespace is set on the context and at the end of flush, context is set back to empty.

Either the documentation or the behavior of flush should be updated.

**Comment by jaredcnance** [comment]
Flush should preserve the namespace. I can’t imagine a scenario where you would want to reuse the logger and not use the same namespace. Will open a PR.
