### ISSUE TITLE
Memory leak in TcpClient

### ISSUE THREAD

**Issue by davidtheclark** [awslabs/aws-embedded-metrics-node#32]
It looks like there's a memory leak in `TcpClient#sendMessage`, making this SDK dangerous for long-running processes.

I wrote some HTTP client code that uses this SDK and makes a request to a simple server every 100ms. I launched the client on ECS, and I saw the memory grow at a steady rate until the task crashed. For a period I ran a revised version of the task that does *not* use the EMF SDK (~16:00-20:00 in the graph below), and during that period memory did not grow — so I know that the EMF SDK is the culprit.

<img width="526" alt="Screen Shot 2020-03-20 at 09 21 39" src="https://user-images.githubusercontent.com/628431/77184806-902ca780-6a8d-11ea-95fe-b09f112a6ac2.png">

I ran the server and client locally with `node --inspect` to see if I could track down the leak. What I found is `JSArrayBufferData` growing with every snapshot and never cleaning up. Looking at the list of retainers, I see that the `TcpClient` seems to be assigning an event listener that is never cleaned.

<img width="1444" alt="Screen Shot 2020-03-20 at 08 17 08" src="https://user-images.githubusercontent.com/628431/77184849-a0dd1d80-6a8d-11ea-8e60-97f6000b599a.png">

This seems to be the responsible code: https://github.com/awslabs/aws-embedded-metrics-node/blob/8bc900218ab18d2fca59bf29211c77d366f83e66/src/sinks/connections/TcpClient.ts#L47-L58

`this.socket.once('error', onSendError)`, specifically. 

I don't understand the purpose served by that listener. If `this.socket.write` fails, there's already code to run `onSendError`. Can we remove that listener completely? Or is there some edge case that it is meant to address?

Another option is to add `this.socket.removeListener('once', onSendError)` inside the callback for `this.socket.write`.

Both of those fixes appeared to cure the memory leak in my local runs. `JSArrayBufferData` stopped growing indefinitely.

<details>
<summary>Here's my client code, for reference:</summary>

```js
'use strict';

require('https').globalAgent.keepAlive = true;
const http = require('http');
const { metricScope } = require('aws-embedded-metrics');

const POLL_TIME = 100;

const serverHost = process.env.ServerHost;
const serverPort = process.env.ServerPort;

const sendRequest = metricScope((metrics) => async () => {
  metrics.setProperty('Role', 'Client');
  metrics.putMetric('ReqCount', 1);

  return new Promise((resolve, reject) => {
    const start = process.hrtime.bigint();
    const handleRes = (res) => {
      res.on('data', () => {});
      res.once('error', (error) => {
        metrics.putMetric('ResError', 1);
        metrics.setProperty('StatusCode', res.statusCode);
        metrics.setProperty('ResErrorData', error);
        reject(error);
      });
      res.on('end', () => {
        const end = process.hrtime.bigint();
        const elapsedMs = Number(end - start) * 1e-6;
        const elapsedMsRounded = Math.round(elapsedMs * 100) / 100; // Round to 2 decimal places.
        metrics.putMetric('ResponseTime', elapsedMsRounded, 'Milliseconds');
        metrics.putMetric('ResSuccess', 1);
        metrics.setProperty('StatusCode', res.statusCode);
        resolve();
      });
    };

    const baseReqOptions = {
      method: 'GET',
      host: serverHost,
      port: serverPort
    };
    metrics.setProperty('ReqOptions', baseReqOptions);

    const req = http.request({ ...baseReqOptions }, handleRes);

    req.once('error', (error) => {
      metrics.putMetric('ReqError', 1);
      metrics.setProperty('ReqErrorData', error);
      reject(error);
    });
    req.end();
  });
});

async function main() {
  setInterval(() => {
    sendRequest().catch((error) => console.error(error));
  }, POLL_TIME);
}

exports.main = main;

if (require.main === module) {
  main().catch((error) => {
    console.error(error);
    process.exit(1);
  });

  process.on('SIGTERM', () => process.exit(0));
}
```

</details>

cc @rclark @springmeyer @danmactough

**Comment by jaredcnance** [comment]
Thanks for reporting this! I’m digging into it now. At first glance I believe you’re right and that the event listener looks redundant. I’ll open a PR to address this shortly. This also reveals a gap in our pre-release integration testing that we need to resolve.

**Comment by jaredcnance** [comment]
I've pushed a fix to `master` and I'm currently configuring our CICD pipeline to run the newly added canaries and will release to npm after a 24 hour bake period.

**Comment by davidtheclark** [comment]
Thanks @jaredcnance for the quick response, and for the thorough approach to testing.

**Comment by jaredcnance** [comment]
Absolutely. Thank you for the detailed big report.
