### ISSUE TITLE
Produce metrics with different dimensions from single log

### ISSUE THREAD

**Issue by davidtheclark** [awslabs/aws-embedded-metrics-node#53]
With the raw embedded metrics format, a single structured log can produce multiple metrics with different dimensions. Here's an example:

```json
{
  "_aws": {
    "Timestamp": 1574109732004,
    "CloudWatchMetrics": [
      {
        "Namespace": "lambda-function-metrics",
        "Dimensions": [["dimension1"]],
        "Metrics": [
          {
            "Name": "metric1"
          }
        ]
      },
      {
        "Namespace": "lambda-function-metrics",
        "Dimensions": [["dimension2"]],
        "Metrics": [
          {
            "Name": "metric2"
          }
        ]
      }
    ]
  },
  "dimension1": "value1",
  "dimension2": "value2",
  "metric1": 100,
  "metric2": 200
}
```

Currently, this is not possible with the EMF SDK for Node.js. I would need to create a new MetricLogger for each distinct list of dimensions. This issue is a feature request to add an interface to the SDK that enables this kind of configuration.

The reason I'd prefer to produce these metrics from a single log line, instead of multiple, is so that I can create just one structured log per "unit of work," as described in [this great AWS Builder's Library article](https://aws.amazon.com/builders-library/instrumenting-distributed-systems-for-operational-visibility).

**Comment by jaredcnance** [comment]
I believe this is a duplicate of #46. Can you review that issue and if it’s the same, can you weigh in on the experience you’d prefer.

**Comment by davidtheclark** [comment]
Agreed. Thanks for pointing that out.
