### ISSUE TITLE
Allow setting Timestamp of a metric.

### ISSUE THREAD

**Issue by Grundlefleck** [awslabs/aws-embedded-metrics-node#61]
There is currently no way to set `MetricsContext.meta.Timestamp` via `metricsScope`.

Assuming the rules for [PutMetricData](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_PutMetricData.html) also apply, it is valid to submit metrics that are not equal to `new Date()`.

I am currently working around this be reimplementing `metricScope()`, instantiating `MetricsContext` and `MetricsLogger` directly, and passing `MetricsContext` to the given handler, so they can do `context.meta.Timestamp = ...`. 

For my purposes passing a single `Date` to `metricScope` would suffice.

I'd be happy to put together a PR if you think setting the Timestamp should be possible.

**Comment by jaredcnance** [comment]
Rather than going through the metricScope, would setting it on the logger work instead like you do with properties today?

**Comment by Grundlefleck** [comment]
Hey @jaredcnance thanks for the prompt response.

Setting the timestamp in the same place as setting properties/dimensions/namespace would be perfect. That's the first place I looked to see if this call was possible.

I only mentioned `metricScope` because it was the easiest workaround I found. I didn't see a way access the context (and `meta.Timestamp`) via the logger.

Do you think it makes sense to add `MetricsLogger.setTimestamp()`?

**Comment by jaredcnance** [comment]
> Do you think it makes sense to add MetricsLogger.setTimestamp()?

Yes, I think that makes the most sense to me.

**Comment by jaredcnance** [comment]
This will be available in the next release.
