### ISSUE TITLE
metriscope returning something that's not a function

### ISSUE THREAD

**Issue by Yannick89-ey** [awslabs/aws-embedded-metrics-node#74]
'use strict';
const { metricScope } = require("aws-embedded-metrics");
const myFunc = metricScope(metrics =>
  async () => {
        var domains = ["google.com"];
        domains.forEach(function(domain){
                var https = require('https');
                var options = {
                        host: domain,
                        port: 443
                };

                var req = https.request(options, function(res) {
                        req.end();
                        const days = Math.floor((new Date(res.connection.getPeerCertificate().valid_to) - new Date()) / 86400000)
                        console.log(days);
                        console.log()
                });

        });
});        
exports.handler = myFunc();

metriscope is not returning a function, having a this error

{
  "errorType": "Runtime.HandlerNotFound",
  "errorMessage": "index.handler is not a function",
  "trace": [
    "Runtime.HandlerNotFound: index.handler is not a function",
    "    at Object.module.exports.load (/var/runtime/UserFunction.js:150:11)",
    "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
    "    at Module._compile (internal/modules/cjs/loader.js:1015:30)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)",
    "    at Module.load (internal/modules/cjs/loader.js:879:32)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:724:14)",
    "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)",
    "    at internal/main/run_main_module.js:17:47"
  ]
}

**Comment by jaredcnance** [comment]
Looks like an issue with the docs. Can you try changing this line `exports.handler = myFunc();` to `exports.handler = myFunc;`?

https://github.com/awslabs/aws-embedded-metrics-node/blob/2ec8a84b7cc6081ff368aff501101a710367c6bb/examples/lambda/src/index.js#L18

**Comment by Yannick89-ey** [comment]
this seems to be throwing the same error

**Comment by jaredcnance** [comment]
That seems unlikely. If `myFunc` were not a function, then the first error should have failed in your original code with `myFunc is not a function` and would have thrown at the assignment of `exports.handler = myFunc()`. However, the error message that indicates `index.handler is not a function`. Meaning that `myFunc` must be a function for `myFunc()` to execute successfully and return something to `exports.handler` that is not a function. 

Can you create a minimal reproducible example and provide the: Lambda runtime version and the library npm version?

**Comment by jaredcnance** [comment]
I copied your function source into a new function verbatim which reproduces the error. Removing the function call subsequently fixes the issue for me on a nodejs12.x runtime. The complete source that works for me:

```js
'use strict';

const { metricScope } = require("aws-embedded-metrics");
const myFunc = metricScope(metrics =>
    async () => {
        var domains = ["google.com"];
        domains.forEach(function (domain) {
            var https = require('https');
            var options = {
                host: domain,
                port: 443
            };

            var req = https.request(options, function (res) {
                req.end();
                const days = Math.floor((new Date(res.connection.getPeerCertificate().valid_to) - new Date()) / 86400000)
                console.log(days);
                console.log();
            });

        });
    });
exports.handler = myFunc; // <--- do not call the function, rather return a reference to the function
```

**Comment by Yannick89-ey** [comment]
worked great, thank you
