### ISSUE TITLE
Application crashes when there's no connection to CloudwatchAgent

### ISSUE THREAD

**Issue by jeroenmeulendijks** [awslabs/aws-embedded-metrics-node#81]
When running in a test environment (Which is similar to a setup on EC2 with a CloudwatchAgent) the whole node.js application crashes when it's unable to push metrics to the Agent and I'm unable to catch the error.

**Steps to reproduce**
- Setup an environment similar to EC2 setup
- Do **not** start a CloudWatchAgent
- Try to push some metrics to the Agent (which of course fails)

**Expected behavior**
- Library emits an error which can be caught to handle it appropriately OR handle the error with a log statement (Both are fine with me, but maybe in general it's better to let the caller handle the error)

**Actual behavior**
- You get a UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 0.0.0.0:25888
- The moment the Agent starts you will see a Error: read ECONNRESET and the application closes

**Root Cause**
I tried to narrow down the problem and it seems that https://github.com/awslabs/aws-embedded-metrics-node/blob/2ec8a84b7cc6081ff368aff501101a710367c6bb/src/logger/MetricsLogger.ts#L50 is missing an await. At least if I add an await here the exception is caught and the Log (https://github.com/awslabs/aws-embedded-metrics-node/blob/master/src/logger/MetricScope.ts#L34) is emitted.

**System Overview**
- Running the CloudWatchAgent in a docker container
- Node v12.16.1
- aws-embedded-metrics-node 2.0.3

**Comment by jaredcnance** [comment]
It looks like you're correct that we need an `await` there. This will at least allow the caller to catch the exception. #36 is also related as it would make it so the caller doesn't need to worry about publish failures.

**Comment by jeroenmeulendijks** [comment]
Thanks for your quick reply. For me personally dropping the metrics is good enough and buffering until the connection is back is a nice to have. Although I directly wander how would that work when running in a lambda function? I would not expect my lambda to wait for pushing metrics.

Any ETA on a fix for this?

**Comment by jaredcnance** [comment]
We can fix this specific issue rather quickly. If you want to open a PR, that can move it a little faster. Otherwise, I can start on it in a few days. The fix itself is quite simple, but we also need a test for it.

Regarding #36, this wouldn't apply to Lambda because we're writing to stdout instead of a TCP socket and the write is synchronous. I can't provide an ETA for #36 yet.
