### ISSUE TITLE
Is it net.Socket.writeable or net.Socket.writable?

### ISSUE THREAD

**Issue by nhira** [awslabs/aws-embedded-metrics-node#90]
https://github.com/awslabs/aws-embedded-metrics-node/blob/5c02526089a10bd19059703b83c9d9f22c08963c/src/sinks/connections/TcpClient.ts#L82

I was just looking at this code for something else and haven't had time to confirm this issue, but it looks like we have a typo here ("writeable" Vs. "writable").

**Comment by mjgp2** [comment]
Yes, this is definitely a bug.

**Comment by markkuhn** [comment]
Thank you for pointing this out @nhira. The tcp client has been updated!
